### ISSUE TITLE
Error Fatal error: Class 'Memcached' not found

### ISSUE THREAD

**Issue by plcosta** [rajabishek/begin#1]
After signing up, I receive this error: 

Error Fatal error: Class 'Memcached' not found in vendor\illuminate\cache\MemcachedConnector.php on line 52

However, the user was save in database.

**Comment by plcosta** [comment]
Temporarily, to solve the problem, I changed my env file.

From:

`CACHE_DRIVER=memcached`
`QUEUE_DRIVER=sync`

To:

`CACHE_DRIVER=array`
`SESSION_DRIVER=cookie`
`QUEUE_DRIVER=database`

**Comment by rajabishek** [comment]
@plcosta Thanks for pointing it out. I have changed the default cache driver to file in the sample environment file.
